-- INSERT TABLE VIP --

INSERT INTO "T_VIP" (PK_ID, LEVEL_USER) values(1,'SILVER');

INSERT INTO "T_VIP" (PK_ID, LEVEL_USER) values(2,'GOLD');

INSERT INTO "T_VIP" (PK_ID, LEVEL_USER) values(3,'PLATINUM');
