-- INSERT TABLE VIP --

INSERT INTO "T_VIP" (PK_ID, LEVEL_USER, TOTAL, PERCENT_DISCOUNT) values(1,'SILVER', 5000000, 5);

INSERT INTO "T_VIP" (PK_ID, LEVEL_USER, TOTAL, PERCENT_DISCOUNT) values(2,'GOLD', 7000000, 10);

INSERT INTO "T_VIP" (PK_ID, LEVEL_USER, TOTAL, PERCENT_DISCOUNT)values(3,'PLATINUM', 10000000, 15);

